# Generated by Django 5.1.4 on 2025-01-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_service_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed')], default='Successful', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CountryCode',
        ),
        migrations.AlterField(
            model_name='service',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_transactions', to='app.service'),
        ),
    ]
